common: &default
  :task_states:
    - duplicate

  :project_states:
    - duplicate

  :project_stages:
    - analysis
    - concepts
    - development
    - review
    - delivery

  :ticket_states:
    - duplicate

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default

