common: &default
  :task_states:
    - duplicate

  :project_states:
    - duplicate

  :project_stages:
    - analysis
    - concepts
    - development
    - review
    - delivery

  :ticket_states:
    - duplicate

  :proposal_hourly_rate: 130
  :proposal_version: 1.0

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default

